name: Deploy to Production

on:
  push:
    branches:
      - main  # zmień na nazwę Twojej domyślnej gałęzi

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Tutaj można dodać kroki do kompilacji, testów, kontroli jakości, itp.

    - name: Deploy to production
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        # Tutaj wpisz komendy lub skrypty, które odpowiadają za wdrożenie do środowiska produkcyjnego
        echo "Deploying to production..."
