name: Documentation Generation

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme  # instaluj potrzebne pakiety, np. Sphinx i odpowiednie motywy

    - name: Build documentation
      run: |
        make html  # komenda do budowania dokumentacji
