name: Database Migration and Configuration

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Migrate database
      run: |
        ssh user@server "cd /path/to/app && python manage.py migrate"  

    - name: Run configuration scripts
      run: |
        ssh user@server "cd /path/to/app && ./configure.sh"  
